// Word Island · Unit 1 (Super Minds pp. 4-21: Friends and At school).
// Pictures live in img/u1/. The first choice of every question is the right one.
WORD_ISLAND_UNITS.u1 = (() => {
  const TOPICS = {
    friends: "Friends",
    numbers: "Numbers",
    alphabet: "The alphabet",
    colours: "Colours",
    things: "School things",
    questions: "Is it a …?",
    classroom: "Classroom language",
    story: "The stories",
    phonics: "Phonics: short a"
  };

  const MAZE = [
    look("m-pen", "things", { i: "pen" }, "a pen", "What's this?", ["a pen", "a pencil", "a ruler"], "It's a pen."),
    look("m-pencil", "things", { i: "pencil" }, "a pencil", "What's this?", ["a pencil", "a pen", "a pencil case"], "It's a pencil."),
    look("m-ruler", "things", { i: "ruler" }, "a ruler", "What's this?", ["a ruler", "a rubber", "a desk"], "It's a ruler."),
    look("m-rubber", "things", { img: "photo-rubber" }, "a rubber", "What's this?", ["a rubber", "a ruler", "a pen"], "It's a rubber."),
    look("m-book", "things", { i: "book" }, "a book", "What's this?", ["a book", "a bag", "a desk"], "It's a book."),
    look("m-notebook", "things", { i: "notebook" }, "a notebook", "What's this?", ["a notebook", "a book", "a pencil"], "It's a notebook."),
    look("m-bag", "things", { img: "photo-bag" }, "a bag", "What's this?", ["a bag", "a book", "a desk"], "It's a bag."),
    look("m-desk", "things", { i: "desk" }, "a desk", "What's this?", ["a desk", "a bag", "a book"], "It's a desk."),
    look("m-pencilcase", "things", { img: "photo-pencilcase" }, "a pencil case", "What's this?", ["a pencil case", "a pencil", "a bag"], "It's a pencil case."),
    look("m-pen2", "things", { img: "photo-pen" }, "a pen", "What's this?", ["a pen", "a pencil", "a pencil case"], "It's a pen, not a pencil.", { challenge: true }),
    look("m-pencilcase2", "things", { i: "pencilcase" }, "a pencil case", "What's this?", ["a pencil case", "a pencil", "a notebook"], "It's a pencil case, not a pencil.", { challenge: true }),
    ...COLOURS.map((c, k) => look(`m-${c}`, "colours", { balloon: c }, `a ${c} balloon`, "What colour is it?",
      [c, COLOURS[(k + 1) % 8], COLOURS[(k + 3) % 8]], `It's ${c}.`)),
    look("m-mix1", "colours", { mix: ["red", "blue"] }, "red and blue paint", "Mix the colours. What colour?", ["purple", "green", "orange"], "Red and blue make purple.", { challenge: true }),
    look("m-mix2", "colours", { mix: ["blue", "yellow"] }, "blue and yellow paint", "Mix the colours. What colour?", ["green", "purple", "orange"], "Blue and yellow make green.", { challenge: true }),
    look("m-mix3", "colours", { mix: ["red", "yellow"] }, "red and yellow paint", "Mix the colours. What colour?", ["orange", "purple", "green"], "Red and yellow make orange.", { challenge: true }),
    ...[3, 5, 6, 7, 8, 10].map((n) => look(`m-n${n}`, "numbers", { count: n }, `${n} pencils`, "How many?",
      [NUM[n], NUM[n - 1], NUM[n === 10 ? 8 : n + 1]], `${cap(NUM[n])} pencils.`)),
    look("m-n9", "numbers", { count: 9 }, "9 pencils", "How many?", ["nine", "ten", "eight"], "Nine pencils.", { challenge: true }),
    look("m-misty", "friends", { img: "misty" }, "Misty", "Who is it?", ["Misty", "Flash", "Whisper"], "It's Misty."),
    look("m-whisper", "friends", { img: "whisper" }, "Whisper", "Who is it?", ["Whisper", "Thunder", "Flash"], "It's Whisper."),
    look("m-flash", "friends", { img: "flash" }, "Flash", "Who is it?", ["Flash", "Misty", "Thunder"], "It's Flash."),
    look("m-thunder", "friends", { img: "thunder" }, "Thunder", "Who is it?", ["Thunder", "Whisper", "Misty"], "It's Thunder."),
    look("m-tabby", "friends", { img: "tabby" }, "Tabby the cat", "Who is it?", ["Tabby", "Flash", "Whisper"], "It's Tabby. Tabby is a cat."),
    look("m-sit", "classroom", { img: "sit" }, "The teacher and a boy", "What does the teacher say?", ["Sit at your desk, please.", "Open your book, please.", "Close your bag, please."], "Sit at your desk, please."),
    look("m-open", "classroom", { img: "open" }, "The teacher and a girl", "What does the teacher say?", ["Open your book, please.", "Close your book, please.", "Sit at your desk, please."], "Open your book, please."),
    look("m-close", "classroom", { img: "close" }, "The teacher and a girl", "What does the teacher say?", ["Close your bag, please.", "Open your bag, please.", "Pass me a pen, please."], "Close your bag, please."),
    look("m-pass", "classroom", { img: "pass" }, "The teacher and a boy", "What does the teacher say?", ["Pass me a pen, please.", "Open your book, please.", "Close your bag, please."], "Pass me a pen, please."),
    look("m-standup", "classroom", { img: "act-standup" }, "A boy", "What does the teacher say?", ["Stand up.", "Turn around.", "Stretch."], "Stand up."),
    look("m-turn", "classroom", { img: "act-turn" }, "A boy", "What does the teacher say?", ["Turn around.", "Stand up.", "Stretch."], "Turn around."),
    look("m-stretch", "classroom", { img: "act-stretch" }, "A boy", "What does the teacher say?", ["Stretch.", "Stand up.", "Turn around."], "Stretch."),
    look("m-takeout", "classroom", { img: "act-takeout" }, "A boy and a box", "What does the teacher say?", ["Take out your pencil case.", "Put the pencil case on your head.", "Stand up."], "Take out your pencil case."),
    look("m-head", "classroom", { img: "act-head" }, "A boy with a pencil case", "What does the teacher say?", ["Put the pencil case on your head.", "Take out your pencil case.", "Look down and catch it."], "Put the pencil case on your head.", { challenge: true }),
    look("m-catch", "classroom", { img: "act-catch" }, "A boy with a pencil case", "What does the teacher say?", ["Look down and catch it.", "Put the pencil case on your head.", "Turn around."], "Look down and catch it.", { challenge: true }),
    look("m-abc1", "alphabet", { abc: "A B C" }, "A, B, C, and then", "What comes next?", ["D", "E", "G"], "A, B, C, D."),
    look("m-abc2", "alphabet", { abc: "H I J" }, "H, I, J, and then", "What comes next?", ["K", "L", "M"], "H, I, J, K."),
    look("m-abc3", "alphabet", { abc: "P Q R" }, "P, Q, R, and then", "What comes next?", ["S", "T", "O"], "P, Q, R, S."),
    look("m-abc4", "alphabet", { abc: "W X Y" }, "W, X, Y, and then", "What comes next?", ["Z", "V", "U"], "W, X, Y, Z."),
    look("m-abc5", "alphabet", { abc: "L M N" }, "L, M, N, and then", "What comes next?", ["O", "P", "Q"], "L, M, N, O.", { challenge: true }),
    look("m-rat", "phonics", { img: "rat" }, "a rat in a bag", "What's this?", ["a rat", "a cat", "a bag"], "A fat rat in a black bag."),
    look("m-cat", "phonics", { img: "tabby" }, "a cat", "What's this?", ["a cat", "a rat", "a bag"], "It's a cat.")
  ];

  const MOLES = [
    ask("o-misty", "friends", { img: "misty" }, "Misty", "What's your name?", ["I'm Misty.", "I'm Flash.", "I'm six."]),
    ask("o-thunder", "friends", { img: "thunder" }, "Thunder", "What's your name?", ["I'm Thunder.", "I'm Whisper.", "I'm four."]),
    ask("o-age6", "friends", { num: 6 }, "six", "How old are you?", ["I'm six.", "I'm Carlos.", "Yes, it is."]),
    ask("o-age7", "friends", { num: 7 }, "seven", "How old are you?", ["I'm seven.", "I'm six.", "It's seven."]),
    ask("o-pen", "questions", { i: "pen" }, "a pen", "Is it a pen?", ["Yes, it is.", "No, it isn't.", "It's a ruler."]),
    ask("o-book", "questions", { i: "book" }, "a book", "Is it a book?", ["Yes, it is.", "No, it isn't.", "It's a pen."]),
    ask("o-bag", "questions", { img: "photo-bag" }, "a bag", "Is it a bag?", ["Yes, it is.", "No, it isn't.", "It's a desk."]),
    ask("o-pencil", "questions", { i: "pencil" }, "a pencil", "Is it a pen?", ["No, it isn't. It's a pencil.", "Yes, it is.", "No, it isn't. It's a ruler."]),
    ask("o-rubber", "questions", { img: "photo-rubber" }, "a rubber", "Is it a ruler?", ["No, it isn't. It's a rubber.", "Yes, it is.", "No, it isn't. It's a pencil."]),
    ask("o-pencilcase", "questions", { img: "photo-pencilcase" }, "a pencil case", "What's this?", ["It's a pencil case.", "It's a pencil.", "Yes, it is."]),
    ask("o-notebook", "questions", { i: "notebook" }, "a notebook", "Is it a book?", ["No, it isn't. It's a notebook.", "Yes, it is.", "No, it isn't. It's a bag."], { challenge: true }),
    ask("o-ruler", "questions", { i: "ruler" }, "a ruler", "Is it a rubber?", ["No, it isn't. It's a ruler.", "Yes, it is.", "No, it isn't. It's a desk."], { challenge: true }),
    ask("o-green", "colours", { balloon: "green" }, "a green balloon", "What colour is it?", ["It's green.", "It's blue.", "Yes, it is."]),
    ask("o-orange", "colours", { balloon: "orange" }, "an orange balloon", "Is it red?", ["No, it isn't. It's orange.", "Yes, it is.", "No, it isn't. It's yellow."]),
    ask("o-purple", "colours", { balloon: "purple" }, "a purple balloon", "Is it purple?", ["Yes, it is.", "No, it isn't. It's blue.", "It's red."]),
    ask("o-mix", "colours", { mix: ["blue", "yellow"] }, "blue and yellow paint", "Mix blue and yellow. What colour is it?", ["It's green.", "It's purple.", "It's orange."], { challenge: true }),
    ask("o-pass", "classroom", { img: "pass" }, "The teacher and a boy", "Pass me a pen, please.", ["Here you are.", "I'm sorry.", "Thank you."]),
    ask("o-pass2", "classroom", { i: "ruler" }, "a ruler", "Pass me a ruler, please.", ["Here you are.", "It's OK.", "I'm six."]),
    ask("o-sorry", "classroom", { img: "sorry" }, "Flash and a man in the street", "I'm sorry.", ["It's OK.", "Here you are.", "Thank you."]),
    ask("o-thanks", "classroom", { img: "pencilcase-story" }, "The Super Friends with Flash's things", "Here's your pencil case.", ["Thank you.", "It's OK.", "I'm sorry."]),
    ask("o-tabbyname", "story", { img: "tabby" }, "Tabby the cat", "What's your name, cat?", ["I'm Tabby.", "I'm four.", "I'm Flash."]),
    ask("o-tabbyage", "story", { img: "tabby" }, "Tabby the cat", "How old are you, Tabby?", ["I'm four.", "I'm six.", "I'm Tabby."]),
    ask("o-lookatme", "story", { quote: "Look at me!" }, "Someone says: Look at me!", "Who says it?", ["Flash.", "Misty.", "Tabby."], { speakQ: "Look at me! Who says it?" }),
    ask("o-myturn", "story", { quote: "My turn. Look!" }, "Someone says: My turn. Look!", "Who says it?", ["Misty.", "Thunder.", "Flash."], { speakQ: "My turn. Look! Who says it?" }),
    ask("o-mybag", "story", { img: "mybag" }, "Flash runs with a bag", "Who says \"My bag!\"?", ["Flash.", "Misty.", "Whisper."], { speakQ: "My bag! Who says it?" }),
    ask("o-animals", "story", { img: "tabby" }, "Tabby the cat", "Who speaks to animals?", ["Whisper.", "Thunder.", "Flash."]),
    ask("o-notebookstory", "story", { quote: "Mum. My notebook!" }, "Someone says: Mum. My notebook!", "Who says it?", ["Flash.", "Thunder.", "Tabby."], { speakQ: "Mum. My notebook! Who says it?", challenge: true }),
    ask("o-rat", "phonics", { img: "rat" }, "a rat in a black bag", "What's in the black bag?", ["A fat rat.", "A fat cat.", "A red pen."])
  ];

  const HANGMAN = [
    spell("h-pen", "things", { i: "pen" }, "a pen", "pen"),
    spell("h-bag", "things", { img: "photo-bag" }, "a bag", "bag"),
    spell("h-book", "things", { i: "book" }, "a book", "book"),
    spell("h-desk", "things", { i: "desk" }, "a desk", "desk"),
    spell("h-ruler", "things", { i: "ruler" }, "a ruler", "ruler"),
    spell("h-rubber", "things", { img: "photo-rubber" }, "a rubber", "rubber"),
    spell("h-pencil", "things", { i: "pencil" }, "a pencil", "pencil"),
    spell("h-notebook", "things", { i: "notebook" }, "a notebook", "notebook", { challenge: true }),
    spell("h-pencilcase", "things", { img: "photo-pencilcase" }, "a pencil case", "pencil case", { challenge: true }),
    ...COLOURS.map((c) => spell(`h-${c}`, "colours", { balloon: c }, `a ${c} balloon`, c,
      c === "purple" || c === "yellow" || c === "orange" ? { challenge: true } : {})),
    ...[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => spell(`h-n${n}`, "numbers", { num: n }, String(n), NUM[n],
      n === 8 ? { challenge: true } : {})),
    spell("h-flash", "friends", { img: "flash" }, "Flash", "Flash"),
    spell("h-misty", "friends", { img: "misty" }, "Misty", "Misty"),
    spell("h-cat", "phonics", { img: "tabby" }, "a cat", "cat"),
    spell("h-rat", "phonics", { img: "rat" }, "a rat", "rat")
  ];

  const PLANES = [
    hear("p-seven", "numbers", "seven", ["7", "1", "3"], { big: true }),
    hear("p-three", "numbers", "three", ["3", "8", "5"], { big: true }),
    hear("p-ten", "numbers", "ten", ["10", "2", "4"], { big: true }),
    hear("p-six", "numbers", "six", ["6", "9", "5"], { big: true }),
    hear("p-nine", "numbers", "nine", ["9", "5", "1"], { big: true }),
    hear("p-g", "alphabet", "G.", ["G", "J", "C"], { big: true, show: "G" }),
    hear("p-y", "alphabet", "Y.", ["Y", "I", "W"], { big: true, show: "Y" }),
    hear("p-b", "alphabet", "B.", ["B", "D", "P"], { big: true, show: "B", challenge: true }),
    hear("p-m", "alphabet", "M.", ["M", "N", "W"], { big: true, show: "M", challenge: true }),
    hear("p-purple", "colours", "purple", ["purple", "red", "green"]),
    hear("p-yellow", "colours", "yellow", ["yellow", "orange", "white"]),
    hear("p-black", "colours", "black", ["black", "blue", "red"]),
    hear("p-pencilcase", "things", "a pencil case", ["pencilcase", "pencil", "bag"], { icons: true }),
    hear("p-notebook", "things", "a notebook", ["notebook", "book", "desk"], { icons: true }),
    hear("p-desk", "things", "a desk", ["desk", "bag", "book"], { icons: true }),
    hear("p-ruler", "things", "a ruler", ["ruler", "rubber", "pen"], { icons: true, challenge: true }),
    hear("p-close", "classroom", "Close your bag, please.", ["Close your bag.", "Open your bag.", "Open your book."]),
    hear("p-sit", "classroom", "Sit at your desk, please.", ["Sit at your desk.", "Stand up.", "Turn around."]),
    hear("p-turn", "classroom", "Turn around.", ["Turn around.", "Stand up.", "Stretch."]),
    hear("p-takeout", "classroom", "Take out your pencil case.", ["Take out your pencil case.", "Put away your book.", "Close your bag."]),
    hear("p-pass", "classroom", "Pass me a ruler, please.", ["Pass me a ruler.", "Pass me a rubber.", "Pass me a pencil."], { challenge: true }),
    hear("p-putaway", "classroom", "Put away your book, please.", ["Put away your book.", "Take out your book.", "Open your book."], { challenge: true }),
    hear("p-thunder", "friends", "Hi, I'm Thunder.", ["Thunder", "Whisper", "Flash"]),
    hear("p-age", "friends", "How old are you? I'm four.", ["4", "6", "10"], { big: true }),
    hear("p-rat", "phonics", "A fat rat in a black bag.", ["a fat rat in a black bag", "a fat cat in a black bag", "a fat rat in a red bag"], { challenge: true })
  ];

  // Teacher explain page: a hint per topic to give before the answer.
  const HINTS = {
    friends: "Remember the Super Friends: Whisper, Thunder, Misty, Flash and Tabby the cat.",
    numbers: "Count with your finger: one, two, three …",
    alphabet: "Sing the alphabet song: A, B, C, D …",
    colours: "Look at the colour. Find something in your room with the same colour.",
    things: "Look at the picture. Is it for writing, for reading, or for carrying things?",
    questions: "Look at the picture first. Is it the same thing as in the question?",
    classroom: "What does the teacher want you to do? Look at the hands and the arrows.",
    story: "Remember the stories. Who runs fast? Who disappears? Who talks to animals?",
    phonics: "Listen for the short a sound: c-a-t, r-a-t, b-a-g."
  };

  // Notes for single questions: a better hint, and why the answer is right.
  const NOTES = {
    "m-pencil": { hint: "Look at the top. Is there a pink rubber?", why: "It's a pencil. It has a sharp grey tip and a rubber on top." },
    "m-pen2": { hint: "Look at the end. Is there a sharp grey tip?", why: "It's a pen. A pen has ink. A pencil has a sharp grey tip." },
    "m-ruler": { why: "It's a ruler. It is long and has lines to measure. A rubber is small and rubs out mistakes." },
    "m-rubber": { why: "It's a rubber. We use it to rub out mistakes. A ruler is long with lines." },
    "m-notebook": { why: "It's a notebook. We write in a notebook. A book has a story to read." },
    "m-pencilcase": { why: "It's a pencil case. We keep pencils and pens in a pencil case." },
    "m-pencilcase2": { hint: "Is it one pencil, or a bag for pencils?", why: "It's a pencil case. We keep pencils and pens in it." },
    "m-mix1": { hint: "Think of grapes.", why: "Red and blue make purple." },
    "m-mix2": { hint: "Think of grass and leaves.", why: "Blue and yellow make green." },
    "m-mix3": { hint: "Think of an orange fruit.", why: "Red and yellow make orange." },
    "m-n9": { hint: "Count slowly. Touch each pencil once.", why: "There are nine pencils. Ten is one more." },
    "m-tabby": { why: "Tabby is the Super Friends' cat." },
    "m-sit": { why: "The arrow points down to the chair: Sit at your desk, please." },
    "m-open": { why: "The arrow shows the book opening: Open your book, please." },
    "m-close": { why: "The arrow shows the bag closing: Close your bag, please." },
    "m-pass": { why: "The boy gives the teacher something: Pass me a pen, please." },
    "m-head": { hint: "Where is the pencil case going? Look at the arrow.", why: "The arrow goes up to his head: Put the pencil case on your head." },
    "m-catch": { hint: "Is the pencil case going up or down?", why: "The pencil case falls down to his hand: Look down and catch it." },
    "m-abc5": { hint: "Sing the alphabet from L.", why: "L, M, N, O, P." },
    "m-rat": { hint: "It has a long tail. It is in the bag.", why: "It's a rat: r-a-t. A fat rat in a black bag." },
    "m-cat": { why: "It's a cat: c-a-t. Tabby is a cat." },
    "o-age6": { hint: "Look at the number.", why: "How old are you? I'm six." },
    "o-age7": { hint: "Look at the number.", why: "How old are you? I'm seven." },
    "o-pencil": { hint: "Is it a pen? Look closely at the tip.", why: "It isn't a pen, so we say No, it isn't. Then we say what it is: It's a pencil." },
    "o-rubber": { why: "It isn't a ruler: No, it isn't. It's a rubber." },
    "o-notebook": { hint: "A book or a notebook? Look at the lines and the rings.", why: "It isn't a book: No, it isn't. It's a notebook." },
    "o-ruler": { hint: "Long with lines, or small and soft?", why: "It's long with lines: No, it isn't. It's a ruler." },
    "o-orange": { why: "The balloon is orange, not red: No, it isn't. It's orange." },
    "o-mix": { why: "Blue and yellow make green: It's green." },
    "o-pass": { hint: "What do we say when we give something?", why: "When we give something to someone, we say: Here you are." },
    "o-pass2": { hint: "What do we say when we give something?", why: "When we give something to someone, we say: Here you are." },
    "o-sorry": { hint: "Someone says sorry. Is it OK?", why: "When someone says I'm sorry, we say: It's OK." },
    "o-thanks": { hint: "What do we say when we get something?", why: "When someone gives us something, we say: Thank you." },
    "o-tabbyage": { hint: "Remember the story: the cat tells them.", why: "In the story, Tabby says: I'm four." },
    "o-lookatme": { hint: "Who can run very fast?", why: "Flash is fast. Flash says: Look at me!" },
    "o-myturn": { hint: "Who can disappear?", why: "Misty can disappear. Misty says: My turn. Look!" },
    "o-mybag": { why: "Flash runs fast to get her bag: My bag!" },
    "o-animals": { hint: "Who talks to Tabby the cat?", why: "Whisper can talk to animals." },
    "o-notebookstory": { hint: "Who forgets her things in the story?", why: "Flash runs home and says: Mum. My notebook!" },
    "o-rat": { why: "A fat rat in a black bag." },
    "p-b": { hint: "Listen: b, d or p?", why: "B, like bag. D is like desk. P is like pen." },
    "p-m": { hint: "Listen: m, n or w?", why: "M, like Misty. N is like nine. W is like Whisper." },
    "p-ruler": { hint: "Ruler or rubber? Listen to the middle of the word.", why: "Ruler: r-u-l-e-r. Rubber: r-u-b-b-e-r." },
    "p-pass": { hint: "Listen to the last word: ruler or rubber?", why: "Pass me a ruler. Ruler has an l. Rubber has two b's." },
    "p-putaway": { hint: "Put away or take out?", why: "Put away your book means put it in your bag." },
    "p-rat": { hint: "Listen for two words: rat and black.", why: "A fat rat in a black bag." }
  };

  return {
    id: "u1",
    number: 1,
    title: "Friends and At school",
    h1: "Pen or pencil?",
    lede: "Names, numbers, colours, school things and the stories. Come to Word Island. Play, and practise.",
    topics: TOPICS,
    hints: HINTS,
    notes: NOTES,
    banks: { maze: MAZE, moles: MOLES, hangman: HANGMAN, planes: PLANES }
  };
})();
