// Word Island · Unit 6 (Super Minds pp. 70-81: The old house).
// Pictures live in img/u6/. The first choice of every question is the right one.
WORD_ISLAND_UNITS.u6 = (() => {
  const TOPICS = {
    rooms: "Rooms in a house",
    there: "There's … / There are …",
    isthere: "Is there …? Are there any …?",
    song: "In my little house",
    story: "At the house",
    phonics: "Phonics: h",
    habitats: "Habitats"
  };

  const MAZE = [
    look("u6m-bathroom", "rooms", { img: "room-bathroom" }, "a room with a bath and a toilet", "Which room is it?", ["the bathroom", "the bedroom", "the kitchen"], "It's the bathroom."),
    look("u6m-bedroom", "rooms", { img: "room-bedroom" }, "a room with a bed", "Which room is it?", ["the bedroom", "the bathroom", "the living room"], "It's the bedroom."),
    look("u6m-living", "rooms", { img: "room-living" }, "a room with a sofa and a lamp", "Which room is it?", ["the living room", "the dining room", "the hall"], "It's the living room."),
    look("u6m-hall", "rooms", { img: "room-hall" }, "a room with a door and a coat stand", "Which room is it?", ["the hall", "the kitchen", "the cellar"], "It's the hall.", { challenge: true }),
    look("u6m-dining", "rooms", { img: "room-dining" }, "a room with a table and chairs", "Which room is it?", ["the dining room", "the living room", "the bedroom"], "It's the dining room."),
    look("u6m-kitchen", "rooms", { img: "room-kitchen" }, "a room with a cooker", "Which room is it?", ["the kitchen", "the bathroom", "the dining room"], "It's the kitchen."),
    look("u6m-stairs", "rooms", { img: "room-stairs" }, "steps going down", "What are these?", ["stairs", "a hall", "a cellar"], "They're stairs."),
    look("u6m-cellar", "rooms", { img: "room-cellar" }, "a dark room under the house", "Which room is it?", ["the cellar", "the bedroom", "the kitchen"], "It's the cellar. It's under the house.", { challenge: true }),
    look("u6m-lizard", "song", { img: "s-lizard" }, "a lizard next to a bed", "Where's the lizard?", ["in the bedroom", "in the bathroom", "in the kitchen"], "There's a lizard in my bedroom."),
    look("u6m-crocs", "song", { img: "s-crocodiles" }, "crocodiles in a bath", "Where are the crocodiles?", ["in the bathroom", "in the garden", "in the cellar"], "There are seven crocodiles in my lovely bathroom."),
    look("u6m-cat", "song", { img: "s-cat" }, "a cat on an armchair", "Where's the cat?", ["in the living room", "in the kitchen", "in the cellar"], "There's a cat in the living room."),
    look("u6m-spider", "song", { img: "s-spider" }, "a spider", "Where's the spider?", ["in the kitchen", "in the bedroom", "in the garden"], "There's a spider in the kitchen."),
    look("u6m-snake", "song", { img: "s-snake" }, "a snake", "Where's the snake?", ["in the cellar", "in the bathroom", "in the living room"], "There's a snake in the cellar.", { challenge: true }),
    look("u6m-tigers", "song", { img: "s-tigers" }, "tigers next to a gate", "Where are the tigers?", ["in the garden", "in the bedroom", "in the kitchen"], "There are tigers, lots of tigers, in my lovely garden."),
    look("u6m-plane", "isthere", { img: "plane" }, "a plane", "What's this?", ["a plane", "a kite", "a car"], "It's a plane."),
    look("u6m-rat", "isthere", { img: "rat" }, "a rat", "What's this?", ["a rat", "a cat", "a bike"], "It's a rat."),
    look("u6m-car", "isthere", { img: "car" }, "a car", "What's this?", ["a car", "a bike", "a plane"], "It's a car."),
    look("u6m-bike", "isthere", { img: "bike" }, "a bike", "What's this?", ["a bike", "a car", "a kite"], "It's a bike."),
    look("u6m-cake", "isthere", { img: "cake" }, "a cake", "What's this?", ["a cake", "a pear", "a hat"], "It's a cake."),
    look("u6m-kite", "isthere", { img: "kite" }, "a kite", "What's this?", ["a kite", "a plane", "a cake"], "It's a kite."),
    look("u6m-pears", "isthere", { img: "pears" }, "two pears", "How many pears are there?", ["There are two pears.", "There's one pear.", "There are three pears."], "There are two pears.", { challenge: true }),
    look("u6m-monster", "there", { img: "monster" }, "a purple monster", "What can you say?", ["There's a monster.", "There are a monster.", "There's monsters."], "There's a monster. One monster: there's."),
    look("u6m-house", "story", { img: "house" }, "a big old house at night", "What's this?", ["the old house", "the park", "the school"], "There's the old house. Let's go in."),
    look("u6m-stairs2", "story", { img: "st-stairs" }, "Misty at the top of old stairs", "What does Misty say?", ["The stairs to the cellar!", "Yuck! Big spiders!", "Here I am."], "The stairs to the cellar! How many are there?"),
    look("u6m-spiders", "story", { img: "st-spiders" }, "Misty with big spiders", "What does Misty say?", ["Yuck! Big spiders!", "Wow! Big rats!", "It's cold here."], "Yuck! Big spiders!"),
    look("u6m-rats", "story", { img: "st-rats" }, "Misty and lots of rats", "What does Misty say?", ["Wow! Big rats!", "Yuck! Big spiders!", "Help!"], "Wow! Big rats!", { challenge: true }),
    look("u6m-cat2", "story", { img: "st-cat" }, "a black cat on the stairs", "It's cold here. What's this?", ["a cat", "a rat", "a spider"], "It's a cat."),
    look("u6m-here", "story", { img: "st-here" }, "Misty comes out of the house to her friends", "What does Misty say?", ["Here I am.", "Go in? No way!", "Yuck! Big spiders!"], "Here I am."),
    look("u6m-hats", "phonics", { img: "hall-hats" }, "a hall full of hats", "What is Harry's hall full of?", ["hats", "cats", "bats"], "Harry's hall is full of hats."),
    look("u6m-polar", "habitats", { img: "polar" }, "white ice and blue water", "What habitat is it?", ["polar region", "desert", "jungle"], "It's a polar region. It's white and blue."),
    look("u6m-ocean", "habitats", { img: "ocean" }, "a big blue wave", "What habitat is it?", ["ocean", "mountains", "desert"], "It's the ocean."),
    look("u6m-jungle", "habitats", { img: "jungle" }, "lots of green trees", "What habitat is it?", ["jungle", "ocean", "polar region"], "It's a jungle. It's green."),
    look("u6m-desert", "habitats", { img: "desert" }, "orange sand under a blue sky", "What habitat is it?", ["desert", "jungle", "ocean"], "It's a desert."),
    look("u6m-mountains", "habitats", { img: "mountains" }, "a tall rocky peak", "What habitat is it?", ["mountains", "polar region", "jungle"], "They're mountains."),
    look("u6m-sand", "habitats", { img: "sand" }, "sand", "What's this?", ["sand", "snow", "rocks"], "It's sand. You find sand in the desert."),
    look("u6m-snow", "habitats", { img: "snow" }, "snow", "What's this?", ["snow", "sand", "coral"], "It's snow. You find snow in the polar regions.", { challenge: true }),
    look("u6m-trees", "habitats", { img: "trees" }, "a big green tree", "What are these?", ["trees", "rocks", "coral"], "They're trees. You find trees in the jungle."),
    look("u6m-rocks", "habitats", { img: "rocks" }, "big grey rocks", "What are these?", ["rocks", "trees", "sand"], "They're rocks."),
    look("u6m-coral", "habitats", { img: "coral" }, "red coral in the sea", "What's this?", ["coral", "trees", "snow"], "It's coral. You find coral in the ocean.", { challenge: true })
  ];

  const MOLES = [
    ask("u6o-sleep", "rooms", { img: "room-bedroom" }, "a bedroom", "Where do you sleep?", ["In the bedroom.", "In the kitchen.", "In the hall."]),
    ask("u6o-cook", "rooms", { img: "room-kitchen" }, "a kitchen", "Where do you cook?", ["In the kitchen.", "In the bathroom.", "In the cellar."]),
    ask("u6o-bath", "rooms", { img: "room-bathroom" }, "a bathroom", "Where do you have a bath?", ["In the bathroom.", "In the living room.", "In the dining room."]),
    ask("u6o-dinner", "rooms", { img: "room-dining" }, "a dining room", "Where do you eat dinner?", ["In the dining room.", "In the bedroom.", "In the cellar."]),
    ask("u6o-tv", "rooms", { img: "room-living" }, "a living room", "Where do you watch TV?", ["In the living room.", "In the bathroom.", "In the hall."], { challenge: true }),
    ask("u6o-park", "isthere", { img: "park" }, "a street next to a park", "Is there a park?", ["Yes, there is.", "Yes, there are.", "No, there aren't."]),
    ask("u6o-bikes", "isthere", { img: "park" }, "a street next to a park", "Are there any bikes?", ["Yes, there are.", "Yes, there is.", "No, there isn't."]),
    ask("u6o-dogs", "isthere", { img: "park" }, "a street next to a park, with cats but no dogs", "Are there any dogs?", ["No, there aren't.", "Yes, there are.", "No, there isn't."], { challenge: true }),
    ask("u6o-plane", "isthere", { img: "plane" }, "a plane", "Is there a plane?", ["Yes, there is.", "Yes, there are.", "No, there aren't."]),
    ask("u6o-rats", "isthere", { quote: "Are there any rats?" }, "Someone asks: Are there any rats?", "There are no rats. What's the answer?", ["No, there aren't.", "No, there isn't.", "Yes, there is."], { speakQ: "Are there any rats? There are no rats. What's the answer?" }),
    ask("u6o-cars", "isthere", { img: "park" }, "a street with four cars", "How many cars are there?", ["There are four cars.", "There's four cars.", "Yes, there are."], { challenge: true }),
    ask("u6o-crocs", "there", { img: "s-crocodiles" }, "crocodiles in a bath", "What can you say?", ["There are seven crocodiles.", "There's seven crocodiles.", "There is a crocodiles."]),
    ask("u6o-tigers", "there", { img: "s-tigers" }, "tigers in a garden", "What can you say?", ["There are tigers in the garden.", "There's tigers in the garden.", "There is a tigers."]),
    ask("u6o-snake", "there", { img: "s-snake" }, "one snake", "What can you say?", ["There's a snake.", "There are a snake.", "There are snakes."]),
    ask("u6o-cat", "song", { quote: "There's a cat in the …" }, "The song says: There's a cat in the …", "Finish the song.", ["living room.", "kitchen.", "cellar."], { speakQ: "There's a cat in the … Finish the song." }),
    ask("u6o-lizard", "song", { img: "s-lizard" }, "a lizard", "Where is the lizard in the song?", ["In the bedroom.", "In the bathroom.", "In the kitchen."], { challenge: true }),
    ask("u6o-goin", "story", { quote: "There's the old house. Let's go in." }, "Misty says: There's the old house. Let's go in.", "What do her friends say?", ["Go in? No way!", "Here I am.", "Wow! Big rats!"], { speakQ: "There's the old house. Let's go in. What do her friends say?" }),
    ask("u6o-where", "story", { quote: "Misty, where are you?" }, "Her friends say: Misty, where are you?", "What does Misty say?", ["Here I am.", "Go in? No way!", "It's cold here."], { speakQ: "Misty, where are you? What does Misty say?" }),
    ask("u6o-brave", "story", { img: "misty" }, "Misty", "Who isn't scared of the house?", ["Misty.", "The rats.", "The spiders."]),
    ask("u6o-wait", "story", { quote: "OK. Let me go in. Wait for me here." }, "Someone says: OK. Let me go in. Wait for me here.", "Who says it?", ["Misty.", "The cat.", "Harry."], { speakQ: "OK. Let me go in. Wait for me here. Who says it?", challenge: true }),
    ask("u6o-harry", "phonics", { img: "hall-hats" }, "Harry in his hall", "Whose hall is full of hats?", ["Harry's.", "Misty's.", "The cat's."]),
    ask("u6o-camel", "habitats", { img: "camel" }, "a camel", "Where do you find camels?", ["In the desert.", "In the ocean.", "In the polar regions."]),
    ask("u6o-tiger", "habitats", { img: "tiger" }, "a tiger", "Where do you find tigers?", ["In the jungle.", "In the desert.", "In the ocean."]),
    ask("u6o-penguin", "habitats", { img: "penguin" }, "a penguin", "Where do you find penguins?", ["In the polar regions.", "In the jungle.", "In the desert."]),
    ask("u6o-shark", "habitats", { img: "shark" }, "a shark", "Where do you find sharks?", ["In the ocean.", "In the mountains.", "In the jungle."]),
    ask("u6o-goat", "habitats", { img: "goat" }, "a goat", "Where do you find goats?", ["In the mountains.", "In the ocean.", "In the polar regions."], { challenge: true }),
    ask("u6o-coral", "habitats", { img: "coral" }, "coral", "Where do you find coral?", ["In the ocean.", "In the mountains.", "In the jungle."], { challenge: true })
  ];

  const HANGMAN = [
    spell("u6h-kitchen", "rooms", { img: "room-kitchen" }, "a kitchen", "kitchen"),
    spell("u6h-bedroom", "rooms", { img: "room-bedroom" }, "a bedroom", "bedroom"),
    spell("u6h-bathroom", "rooms", { img: "room-bathroom" }, "a bathroom", "bathroom", { challenge: true }),
    spell("u6h-hall", "rooms", { img: "room-hall" }, "a hall", "hall"),
    spell("u6h-stairs", "rooms", { img: "room-stairs" }, "stairs", "stairs"),
    spell("u6h-cellar", "rooms", { img: "room-cellar" }, "a cellar", "cellar", { challenge: true }),
    spell("u6h-house", "story", { img: "house" }, "a house", "house"),
    spell("u6h-spider", "song", { img: "s-spider" }, "a spider", "spider"),
    spell("u6h-snake", "song", { img: "s-snake" }, "a snake", "snake"),
    spell("u6h-lizard", "song", { img: "s-lizard" }, "a lizard", "lizard"),
    spell("u6h-rat", "isthere", { img: "rat" }, "a rat", "rat"),
    spell("u6h-kite", "isthere", { img: "kite" }, "a kite", "kite"),
    spell("u6h-cake", "isthere", { img: "cake" }, "a cake", "cake"),
    spell("u6h-plane", "isthere", { img: "plane" }, "a plane", "plane"),
    spell("u6h-hat", "phonics", { img: "hall-hats" }, "hats", "hat"),
    spell("u6h-tiger", "habitats", { img: "tiger" }, "a tiger", "tiger"),
    spell("u6h-camel", "habitats", { img: "camel" }, "a camel", "camel"),
    spell("u6h-shark", "habitats", { img: "shark" }, "a shark", "shark"),
    spell("u6h-sand", "habitats", { img: "sand" }, "sand", "sand"),
    spell("u6h-snow", "habitats", { img: "snow" }, "snow", "snow"),
    spell("u6h-jungle", "habitats", { img: "jungle" }, "a jungle", "jungle", { challenge: true }),
    spell("u6h-penguin", "habitats", { img: "penguin" }, "a penguin", "penguin", { challenge: true })
  ];

  const PLANES = [
    hear("u6p-kitchen", "rooms", "the kitchen", ["room-kitchen", "room-bathroom", "room-hall"], { pics: true, alts: ["kitchen", "bathroom", "hall"] }),
    hear("u6p-bedroom", "rooms", "the bedroom", ["room-bedroom", "room-living", "room-dining"], { pics: true, alts: ["bedroom", "living room", "dining room"] }),
    hear("u6p-dining", "rooms", "the dining room", ["room-dining", "room-living", "room-kitchen"], { pics: true, alts: ["dining room", "living room", "kitchen"] }),
    hear("u6p-cellar", "rooms", "the cellar", ["room-cellar", "room-stairs", "room-hall"], { pics: true, alts: ["cellar", "stairs", "hall"], challenge: true }),
    hear("u6p-living", "rooms", "the living room", ["living room", "dining room", "bathroom"], { challenge: true }),
    hear("u6p-hall", "rooms", "the hall", ["hall", "house", "hat"]),
    hear("u6p-plane", "isthere", "Is there a plane?", ["plane", "kite", "car"], { pics: true, alts: ["a plane", "a kite", "a car"] }),
    hear("u6p-bike", "isthere", "Is there a bike?", ["bike", "gokart", "car"], { pics: true, alts: ["a bike", "a go-kart", "a car"] }),
    hear("u6p-rat", "isthere", "Are there any rats?", ["rat", "cake", "pears"], { pics: true, alts: ["rats", "cakes", "pears"] }),
    hear("u6p-yes-are", "isthere", "Are there any bikes? Yes, there are.", ["Yes, there are.", "Yes, there is.", "No, there aren't."], { challenge: true }),
    hear("u6p-cars", "isthere", "How many cars are there? There are four cars.", ["4", "3", "5"], { big: true, show: "There are four cars." }),
    hear("u6p-monster", "there", "There's a monster.", ["There's a monster.", "There are four cats.", "There's a cat."]),
    hear("u6p-crocs", "song", "There are seven crocodiles in my lovely bathroom.", ["s-crocodiles", "s-lizard", "s-tigers"], { pics: true, alts: ["crocodiles in the bathroom", "a lizard in the bedroom", "tigers in the garden"] }),
    hear("u6p-spider", "song", "There's a spider in the kitchen.", ["s-spider", "s-cat", "s-snake"], { pics: true, alts: ["a spider in the kitchen", "a cat in the living room", "a snake in the cellar"] }),
    hear("u6p-snake", "song", "There's a snake in the cellar.", ["s-snake", "s-lizard", "s-spider"], { pics: true, alts: ["a snake in the cellar", "a lizard in the bedroom", "a spider in the kitchen"], challenge: true }),
    hear("u6p-spiders", "story", "Yuck! Big spiders!", ["Yuck! Big spiders!", "Wow! Big rats!", "Here I am."]),
    hear("u6p-noway", "story", "Go in? No way!", ["Go in? No way!", "Let's go in.", "Help!"]),
    hear("u6p-cold", "story", "It's cold here. What's this?", ["It's cold here.", "It's cold today.", "It's hot here."], { challenge: true }),
    hear("u6p-hats", "phonics", "Harry's hall is full of hats.", ["Harry's hall is full of hats.", "Harry's hall is full of cats.", "Harry's house is full of hats."], { challenge: true }),
    hear("u6p-polarbear", "habitats", "a polar bear", ["polarbear", "penguin", "goat"], { pics: true, alts: ["a polar bear", "a penguin", "a goat"] }),
    hear("u6p-parrot", "habitats", "a parrot", ["parrot", "tiger", "camel"], { pics: true, alts: ["a parrot", "a tiger", "a camel"] }),
    hear("u6p-jellyfish", "habitats", "a jellyfish", ["jellyfish", "shark", "penguin"], { pics: true, alts: ["a jellyfish", "a shark", "a penguin"] }),
    hear("u6p-desert", "habitats", "You find sand in the desert.", ["desert", "ocean", "jungle"], { pics: true, alts: ["the desert", "the ocean", "the jungle"] }),
    hear("u6p-mountains", "habitats", "mountains", ["mountains", "polar", "jungle"], { pics: true, alts: ["mountains", "polar region", "jungle"], challenge: true })
  ];

  // Teacher explain page: a hint per topic to give before the answer.
  const HINTS = {
    rooms: "Look for the furniture: a bed, a bath, a cooker, a table, a sofa …",
    there: "One thing: There's a … More than one: There are …",
    isthere: "Is there a …? → Yes, there is. Are there any …? → Yes, there are. / No, there aren't.",
    song: "Sing the song In my little house. Which animal is in which room?",
    story: "Remember the story At the house. Misty goes into the old house alone.",
    phonics: "Listen for the h sound at the start: h-all, h-at, H-arry.",
    habitats: "Is it hot or cold? Wet or dry? Think of the colours: white, blue, green, yellow."
  };

  // Notes for single questions: a better hint, and why the answer is right.
  const NOTES = {
    "u6m-here": { why: "Misty was invisible. Now her friends can see her: Here I am." },
    "u6m-hall": { hint: "Look for the front door and the coat stand.", why: "The hall is by the front door. You put your coat there." },
    "u6m-cellar": { hint: "Is it at the top or the bottom of the house?", why: "The cellar is under the house, at the bottom of the stairs." },
    "u6m-stairs": { why: "Stairs go up and down. One stair, two stairs: they're stairs." },
    "u6m-snake": { hint: "Sing the song: There's a snake in the …", why: "The song says: There's a snake in the cellar." },
    "u6m-crocs": { why: "The song says: There are seven crocodiles in my lovely bathroom. They are in the bath!" },
    "u6m-pears": { hint: "Count them: one, two …", why: "Two pears: more than one, so There are two pears." },
    "u6m-monster": { hint: "One monster or lots of monsters?", why: "One monster: There's a monster." },
    "u6m-rats": { hint: "Spiders or rats? Look at the animals.", why: "There are lots of rats: Wow! Big rats!" },
    "u6m-snow": { hint: "Is it hot or cold?", why: "Snow is cold and white. Sand is hot and yellow." },
    "u6m-coral": { hint: "Is it on land or under the sea?", why: "Coral lives in the ocean. It's not a tree." },
    "u6m-polar": { why: "The polar regions are white and blue: ice, snow and cold water." },
    "u6o-tv": { why: "We watch TV on the sofa in the living room." },
    "u6o-bikes": { hint: "Any bikes: one or lots? Listen to Are there.", why: "Are there any bikes? Yes, there are." },
    "u6o-dogs": { hint: "Look at the picture. Can you see a dog?", why: "There are cats, but no dogs: No, there aren't." },
    "u6o-rats": { why: "Are there any …? The answer is: No, there aren't." },
    "u6o-cars": { hint: "Count the cars: pink, green, blue, black.", why: "Four cars: more than one, so There are four cars." },
    "u6o-crocs": { why: "Seven crocodiles: more than one, so There are seven crocodiles." },
    "u6o-tigers": { why: "Lots of tigers: There are tigers in the garden." },
    "u6o-snake": { why: "One snake: There's a snake." },
    "u6o-lizard": { hint: "Sing: There's a lizard in my …", why: "The song says: There's a lizard in my bedroom." },
    "u6o-goin": { why: "Her friends are scared: Go in? No way!" },
    "u6o-where": { why: "Misty is invisible. She says: Here I am." },
    "u6o-brave": { why: "Misty goes into the old house alone. She isn't scared." },
    "u6o-wait": { hint: "Who goes into the house?", why: "Misty goes in. She says: OK. Let me go in. Wait for me here." },
    "u6o-goat": { hint: "Goats like to climb.", why: "You find goats in the mountains." },
    "u6o-coral": { why: "You find coral in the ocean, under the water." },
    "u6o-penguin": { why: "Penguins live where it is cold, in the polar regions." },
    "u6p-cellar": { hint: "Under the house, or the steps?", why: "The cellar is the room under the house." },
    "u6p-living": { hint: "Listen: living or dining?", why: "The living room: we sit and watch TV there. The dining room: we eat there." },
    "u6p-yes-are": { hint: "Bikes: one or lots? Listen for are.", why: "Are there any bikes? Yes, there are." },
    "u6p-cars": { why: "There are four cars." },
    "u6p-snake": { why: "The song says: There's a snake in the cellar." },
    "u6p-cold": { hint: "Listen: cold or hot? here or today?", why: "Misty says: It's cold here. What's this?" },
    "u6p-hats": { hint: "Listen: hats or cats? hall or house?", why: "Harry's hall is full of hats: h, h, h." },
    "u6p-mountains": { why: "Mountains are very high, with rocks." },
    "u6p-desert": { why: "You find sand in the desert." }
  };

  return {
    id: "u6",
    number: 6,
    title: "The old house",
    h1: "Is there a cellar?",
    lede: "Rooms in a house, There's / There are, Is there …?, the story At the house, and habitats. Come to Word Island. Play, and practise.",
    topics: TOPICS,
    hints: HINTS,
    notes: NOTES,
    banks: { maze: MAZE, moles: MOLES, hangman: HANGMAN, planes: PLANES }
  };
})();
